version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-ci
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - ci-network
    restart: unless-stopped

  maven-container:
    build:
      context: .
      dockerfile: Dockerfile.maven
    container_name: maven1
    ports:
      - "8081:8080"
      - "22:22"
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - ci-network
    restart: unless-stopped
    tty: true
    stdin_open: true

networks:
  ci-network:
    driver: bridge

volumes:
  jenkins_home: